name: autoMerge

on:
  push:
    branches:
      - feature/*
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        run: |
          curl \
          -X POST \
          -H "accept: application/vnd.github+json" \
          -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/yyqingshui/ci-ci/merges \
          -d '{"base":"develop","head": "${{ github.ref }}" }'
