name: autoMerge

on:
  push:
    branches:
      - master
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token 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" \
          https://api.github.com/repos/yyqingshui/ci-ci/merges \
          -d '{"base":"develop","head":"master"}'
