name: autoMerge

on:
  push:
    branches:
      - master
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token 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" \
          https://api.github.com/repos/yyqingshui/ci-ci/merges \
          -d '{"base":"develop","head":"master"}'
